version: "3"
services:
  nginx:
    build:
      context: ./.docker
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
    networks:
      - internal
    volumes:
      - .:/var/www/html
    user: ${UID}:${GID}
    depends_on:
      - php
  php:
    build:
      context: ./.docker
      dockerfile: php/Dockerfile
      args:
        USER_ID: ${UID:-0}
        GROUP_ID: ${GID:-0}
        INSTALL_REDIS: "false"
        DB_DRIVER: "mysql"
    tty: true
    environment:
      XDEBUG_MODE: debug
      XDEBUG_SESSION_START: 1
      XDEBUG_CONFIG: client_host=localhost client_port=9003 discover_client_host=true start_on_request=yes
    networks:
      - internal
    volumes:
      - .:/var/www/html
    user: ${UID}:${GID}
    depends_on:
      - db
  composer:
    image: composer
    volumes:
      - .:/app
    user: ${UID}:${GID}
    depends_on:
      - php
    command: composer install
  db:
    image: mysql
    restart: unless-stopped
    volumes:
      - ./.docker/db/initdb/:/docker-entrypoint-initdb.d/
    networks:
      - internal
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: app
      MYSQL_USER: php
      MYSQL_PASSWORD: 123456 
    user: ${UID}:${GID}
networks:
  internal:
    driver: bridge